name: mm_ajanda
description: Scheduler, Task Manager, Chat & more.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.2.0
  dot_navigation_bar: ^1.0.1+3
  syncfusion_flutter_calendar: ^19.4.48
  timelines: ^0.1.0
  email_validator: ^2.0.1
  # google_fonts: ^2.3.0 it does not work with flutter version 2.5.2 instead use the version below:
  google_fonts: 2.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo-momentomedya.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700