// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0XliR4hrnMitbvaAT0G18uYxkP_PHB2Q',
    appId: '1:987779846673:web:8372817fa6d36a3a7d17b0',
    messagingSenderId: '987779846673',
    projectId: 'mm-ajanda',
    authDomain: 'mm-ajanda.firebaseapp.com',
    storageBucket: 'mm-ajanda.appspot.com',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6u4Fw40BYTqm5-KZZ65yx4_hTXPA9iiE',
    appId: '1:987779846673:android:2def0a3976e93f527d17b0',
    messagingSenderId: '987779846673',
    projectId: 'mm-ajanda',
    storageBucket: 'mm-ajanda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxiXYadii4MhtBn2t1UFoBJ1zu_NT6-vA',
    appId: '1:987779846673:ios:0ec251bdc230169f7d17b0',
    messagingSenderId: '987779846673',
    projectId: 'mm-ajanda',
    storageBucket: 'mm-ajanda.appspot.com',
    iosClientId: '987779846673-phnig5hpqss0qn46210jikthcml2rnnb.apps.googleusercontent.com',
    iosBundleId: 'group.momentomedia',
  );
}
